### PR TITLE
fix footer icon + organize the theme

### PR DESCRIPTION
**Pull request by AemieJ**
This PR makes the following changes to the design of the website: 
- The color of the title didn't match the theme of the website logo hence the gradients used in the title have been changed.
- Within the footer on hovering of the social icons, it had a transformation of 360 which isn't user-friendly animation hence I have removed that and made use of the `scale` transformation property only.
- On reaching the bottom of the page, the color of the social icons used to change whereas the progress bar didn't and it seemed quite odd, thus on reaching the bottom of the page, both color effects are observed. 
- The color of the social icons have been modified to match the theme of the website. 

### Preview of the changes 
Screenshot 2020-10-05 at 2 53 14 PM

### CODE REVIEW

**Comment by Ujjwal0501** [comment]
> This PR makes the following changes to the design of the website:
> 
> * The color of the title didn't match the theme of the website logo hence the gradients used in the title have been changed.

This makes the entire page monotonous IMO.

> * Within the footer on hovering of the social icons, it had a transformation of 360 which isn't user-friendly animation hence I have removed that and made use of the `scale` transformation property only.

A very friendly change.

> * On reaching the bottom of the page, the color of the social icons used to change whereas the progress bar didn't and it seemed quite odd, thus on reaching the bottom of the page, both color effects are observed.

I think it's better to not change the bar colour, this distinguishes the interactive content from non-interactive content.

> * The color of the social icons have been modified to match the theme of the website.

I don't have a clear opinion on this.



@Sharma-Hrishabh @johnsoncarl wdyt

**Review by Sharma-Hrishabh — COMMENTED** [review]
@Ujjwal0501 the new color scheme looks decent to me.
I think the suggested changes have solid reasons behind them. So, LGTM.

**Comment by johnsoncarl** [comment]
Looks much better!

**Comment by AemieJ** [comment]
@Ujjwal0501 I agree with its monotonous, what we can do is select a proper palette for the website so it is used everywhere. 'Cause the green in the logo doesn't suit with blue shade.

**Review by Ujjwal0501 — APPROVED** [review]

**Comment by Ujjwal0501** [comment]
I understand the intent. It was a personal opinion; there is no problem with these changes. So merged.

**Pull request merged**
